networks:
  steam_invite_network:
    external: False
volumes:
  db_vol:
    external: False

services:
  steam_invite_discord_bot:
    image: steam_invite_discord_bot:latest
    container_name: steam_invite_discord_bot
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      STEAM_TOKEN:

      DISCORD_TOKEN:
      DISCORD_PREFIX: s.
      DISCORD_DESCRIPTION:

      DB_PORT: 5432
      DB_HOST: steam_invite_db
      DB_USERNAME: username
      DB_PASSWORD: password
      DB_DATABASE: steam_invite

    networks:
      steam_invite_network:
    depends_on:
      - steam_invite_db

  steam_invite_db:
    image: postgres:latest
    container_name: steam_invite_db
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
      POSTGRES_DB: steam_invite
    volumes:
      - db_vol:/var/lib/postgresql/data:rw
      - ./db/PG_SKEL.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      steam_invite_network:
